/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: lizardsNroachesNwasps.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "lizardsNroachesNwasps.pb-c.h"
void   lizard_connect_resp__init
                     (LizardConnectResp         *message)
{
  static const LizardConnectResp init_value = LIZARD_CONNECT_RESP__INIT;
  *message = init_value;
}
size_t lizard_connect_resp__get_packed_size
                     (const LizardConnectResp *message)
{
  assert(message->base.descriptor == &lizard_connect_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lizard_connect_resp__pack
                     (const LizardConnectResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lizard_connect_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lizard_connect_resp__pack_to_buffer
                     (const LizardConnectResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lizard_connect_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LizardConnectResp *
       lizard_connect_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LizardConnectResp *)
     protobuf_c_message_unpack (&lizard_connect_resp__descriptor,
                                allocator, len, data);
}
void   lizard_connect_resp__free_unpacked
                     (LizardConnectResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lizard_connect_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   lizard_movement_req__init
                     (LizardMovementReq         *message)
{
  static const LizardMovementReq init_value = LIZARD_MOVEMENT_REQ__INIT;
  *message = init_value;
}
size_t lizard_movement_req__get_packed_size
                     (const LizardMovementReq *message)
{
  assert(message->base.descriptor == &lizard_movement_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lizard_movement_req__pack
                     (const LizardMovementReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lizard_movement_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lizard_movement_req__pack_to_buffer
                     (const LizardMovementReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lizard_movement_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LizardMovementReq *
       lizard_movement_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LizardMovementReq *)
     protobuf_c_message_unpack (&lizard_movement_req__descriptor,
                                allocator, len, data);
}
void   lizard_movement_req__free_unpacked
                     (LizardMovementReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lizard_movement_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   lizard_movement_resp__init
                     (LizardMovementResp         *message)
{
  static const LizardMovementResp init_value = LIZARD_MOVEMENT_RESP__INIT;
  *message = init_value;
}
size_t lizard_movement_resp__get_packed_size
                     (const LizardMovementResp *message)
{
  assert(message->base.descriptor == &lizard_movement_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lizard_movement_resp__pack
                     (const LizardMovementResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lizard_movement_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lizard_movement_resp__pack_to_buffer
                     (const LizardMovementResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lizard_movement_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LizardMovementResp *
       lizard_movement_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LizardMovementResp *)
     protobuf_c_message_unpack (&lizard_movement_resp__descriptor,
                                allocator, len, data);
}
void   lizard_movement_resp__free_unpacked
                     (LizardMovementResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lizard_movement_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   roaches_connect_req__init
                     (RoachesConnectReq         *message)
{
  static const RoachesConnectReq init_value = ROACHES_CONNECT_REQ__INIT;
  *message = init_value;
}
size_t roaches_connect_req__get_packed_size
                     (const RoachesConnectReq *message)
{
  assert(message->base.descriptor == &roaches_connect_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t roaches_connect_req__pack
                     (const RoachesConnectReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &roaches_connect_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t roaches_connect_req__pack_to_buffer
                     (const RoachesConnectReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &roaches_connect_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RoachesConnectReq *
       roaches_connect_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RoachesConnectReq *)
     protobuf_c_message_unpack (&roaches_connect_req__descriptor,
                                allocator, len, data);
}
void   roaches_connect_req__free_unpacked
                     (RoachesConnectReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &roaches_connect_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   roaches_connect_resp__init
                     (RoachesConnectResp         *message)
{
  static const RoachesConnectResp init_value = ROACHES_CONNECT_RESP__INIT;
  *message = init_value;
}
size_t roaches_connect_resp__get_packed_size
                     (const RoachesConnectResp *message)
{
  assert(message->base.descriptor == &roaches_connect_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t roaches_connect_resp__pack
                     (const RoachesConnectResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &roaches_connect_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t roaches_connect_resp__pack_to_buffer
                     (const RoachesConnectResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &roaches_connect_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RoachesConnectResp *
       roaches_connect_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RoachesConnectResp *)
     protobuf_c_message_unpack (&roaches_connect_resp__descriptor,
                                allocator, len, data);
}
void   roaches_connect_resp__free_unpacked
                     (RoachesConnectResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &roaches_connect_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   roaches_movement_req__init
                     (RoachesMovementReq         *message)
{
  static const RoachesMovementReq init_value = ROACHES_MOVEMENT_REQ__INIT;
  *message = init_value;
}
size_t roaches_movement_req__get_packed_size
                     (const RoachesMovementReq *message)
{
  assert(message->base.descriptor == &roaches_movement_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t roaches_movement_req__pack
                     (const RoachesMovementReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &roaches_movement_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t roaches_movement_req__pack_to_buffer
                     (const RoachesMovementReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &roaches_movement_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RoachesMovementReq *
       roaches_movement_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RoachesMovementReq *)
     protobuf_c_message_unpack (&roaches_movement_req__descriptor,
                                allocator, len, data);
}
void   roaches_movement_req__free_unpacked
                     (RoachesMovementReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &roaches_movement_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   roaches_movement_resp__init
                     (RoachesMovementResp         *message)
{
  static const RoachesMovementResp init_value = ROACHES_MOVEMENT_RESP__INIT;
  *message = init_value;
}
size_t roaches_movement_resp__get_packed_size
                     (const RoachesMovementResp *message)
{
  assert(message->base.descriptor == &roaches_movement_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t roaches_movement_resp__pack
                     (const RoachesMovementResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &roaches_movement_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t roaches_movement_resp__pack_to_buffer
                     (const RoachesMovementResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &roaches_movement_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RoachesMovementResp *
       roaches_movement_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RoachesMovementResp *)
     protobuf_c_message_unpack (&roaches_movement_resp__descriptor,
                                allocator, len, data);
}
void   roaches_movement_resp__free_unpacked
                     (RoachesMovementResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &roaches_movement_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   wasps_connect_req__init
                     (WaspsConnectReq         *message)
{
  static const WaspsConnectReq init_value = WASPS_CONNECT_REQ__INIT;
  *message = init_value;
}
size_t wasps_connect_req__get_packed_size
                     (const WaspsConnectReq *message)
{
  assert(message->base.descriptor == &wasps_connect_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t wasps_connect_req__pack
                     (const WaspsConnectReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &wasps_connect_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t wasps_connect_req__pack_to_buffer
                     (const WaspsConnectReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &wasps_connect_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
WaspsConnectReq *
       wasps_connect_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (WaspsConnectReq *)
     protobuf_c_message_unpack (&wasps_connect_req__descriptor,
                                allocator, len, data);
}
void   wasps_connect_req__free_unpacked
                     (WaspsConnectReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &wasps_connect_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   wasps_connect_resp__init
                     (WaspsConnectResp         *message)
{
  static const WaspsConnectResp init_value = WASPS_CONNECT_RESP__INIT;
  *message = init_value;
}
size_t wasps_connect_resp__get_packed_size
                     (const WaspsConnectResp *message)
{
  assert(message->base.descriptor == &wasps_connect_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t wasps_connect_resp__pack
                     (const WaspsConnectResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &wasps_connect_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t wasps_connect_resp__pack_to_buffer
                     (const WaspsConnectResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &wasps_connect_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
WaspsConnectResp *
       wasps_connect_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (WaspsConnectResp *)
     protobuf_c_message_unpack (&wasps_connect_resp__descriptor,
                                allocator, len, data);
}
void   wasps_connect_resp__free_unpacked
                     (WaspsConnectResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &wasps_connect_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   wasps_movement_req__init
                     (WaspsMovementReq         *message)
{
  static const WaspsMovementReq init_value = WASPS_MOVEMENT_REQ__INIT;
  *message = init_value;
}
size_t wasps_movement_req__get_packed_size
                     (const WaspsMovementReq *message)
{
  assert(message->base.descriptor == &wasps_movement_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t wasps_movement_req__pack
                     (const WaspsMovementReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &wasps_movement_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t wasps_movement_req__pack_to_buffer
                     (const WaspsMovementReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &wasps_movement_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
WaspsMovementReq *
       wasps_movement_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (WaspsMovementReq *)
     protobuf_c_message_unpack (&wasps_movement_req__descriptor,
                                allocator, len, data);
}
void   wasps_movement_req__free_unpacked
                     (WaspsMovementReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &wasps_movement_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   wasps_movement_resp__init
                     (WaspsMovementResp         *message)
{
  static const WaspsMovementResp init_value = WASPS_MOVEMENT_RESP__INIT;
  *message = init_value;
}
size_t wasps_movement_resp__get_packed_size
                     (const WaspsMovementResp *message)
{
  assert(message->base.descriptor == &wasps_movement_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t wasps_movement_resp__pack
                     (const WaspsMovementResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &wasps_movement_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t wasps_movement_resp__pack_to_buffer
                     (const WaspsMovementResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &wasps_movement_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
WaspsMovementResp *
       wasps_movement_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (WaspsMovementResp *)
     protobuf_c_message_unpack (&wasps_movement_resp__descriptor,
                                allocator, len, data);
}
void   wasps_movement_resp__free_unpacked
                     (WaspsMovementResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &wasps_movement_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   lizard_disconnect_req__init
                     (LizardDisconnectReq         *message)
{
  static const LizardDisconnectReq init_value = LIZARD_DISCONNECT_REQ__INIT;
  *message = init_value;
}
size_t lizard_disconnect_req__get_packed_size
                     (const LizardDisconnectReq *message)
{
  assert(message->base.descriptor == &lizard_disconnect_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lizard_disconnect_req__pack
                     (const LizardDisconnectReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lizard_disconnect_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lizard_disconnect_req__pack_to_buffer
                     (const LizardDisconnectReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lizard_disconnect_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LizardDisconnectReq *
       lizard_disconnect_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LizardDisconnectReq *)
     protobuf_c_message_unpack (&lizard_disconnect_req__descriptor,
                                allocator, len, data);
}
void   lizard_disconnect_req__free_unpacked
                     (LizardDisconnectReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lizard_disconnect_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   lizard_disconnect_resp__init
                     (LizardDisconnectResp         *message)
{
  static const LizardDisconnectResp init_value = LIZARD_DISCONNECT_RESP__INIT;
  *message = init_value;
}
size_t lizard_disconnect_resp__get_packed_size
                     (const LizardDisconnectResp *message)
{
  assert(message->base.descriptor == &lizard_disconnect_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lizard_disconnect_resp__pack
                     (const LizardDisconnectResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lizard_disconnect_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lizard_disconnect_resp__pack_to_buffer
                     (const LizardDisconnectResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lizard_disconnect_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LizardDisconnectResp *
       lizard_disconnect_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LizardDisconnectResp *)
     protobuf_c_message_unpack (&lizard_disconnect_resp__descriptor,
                                allocator, len, data);
}
void   lizard_disconnect_resp__free_unpacked
                     (LizardDisconnectResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lizard_disconnect_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   roaches_disconnect_req__init
                     (RoachesDisconnectReq         *message)
{
  static const RoachesDisconnectReq init_value = ROACHES_DISCONNECT_REQ__INIT;
  *message = init_value;
}
size_t roaches_disconnect_req__get_packed_size
                     (const RoachesDisconnectReq *message)
{
  assert(message->base.descriptor == &roaches_disconnect_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t roaches_disconnect_req__pack
                     (const RoachesDisconnectReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &roaches_disconnect_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t roaches_disconnect_req__pack_to_buffer
                     (const RoachesDisconnectReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &roaches_disconnect_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RoachesDisconnectReq *
       roaches_disconnect_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RoachesDisconnectReq *)
     protobuf_c_message_unpack (&roaches_disconnect_req__descriptor,
                                allocator, len, data);
}
void   roaches_disconnect_req__free_unpacked
                     (RoachesDisconnectReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &roaches_disconnect_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   roaches_disconnect_resp__init
                     (RoachesDisconnectResp         *message)
{
  static const RoachesDisconnectResp init_value = ROACHES_DISCONNECT_RESP__INIT;
  *message = init_value;
}
size_t roaches_disconnect_resp__get_packed_size
                     (const RoachesDisconnectResp *message)
{
  assert(message->base.descriptor == &roaches_disconnect_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t roaches_disconnect_resp__pack
                     (const RoachesDisconnectResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &roaches_disconnect_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t roaches_disconnect_resp__pack_to_buffer
                     (const RoachesDisconnectResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &roaches_disconnect_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RoachesDisconnectResp *
       roaches_disconnect_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RoachesDisconnectResp *)
     protobuf_c_message_unpack (&roaches_disconnect_resp__descriptor,
                                allocator, len, data);
}
void   roaches_disconnect_resp__free_unpacked
                     (RoachesDisconnectResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &roaches_disconnect_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   wasps_disconnect_req__init
                     (WaspsDisconnectReq         *message)
{
  static const WaspsDisconnectReq init_value = WASPS_DISCONNECT_REQ__INIT;
  *message = init_value;
}
size_t wasps_disconnect_req__get_packed_size
                     (const WaspsDisconnectReq *message)
{
  assert(message->base.descriptor == &wasps_disconnect_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t wasps_disconnect_req__pack
                     (const WaspsDisconnectReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &wasps_disconnect_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t wasps_disconnect_req__pack_to_buffer
                     (const WaspsDisconnectReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &wasps_disconnect_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
WaspsDisconnectReq *
       wasps_disconnect_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (WaspsDisconnectReq *)
     protobuf_c_message_unpack (&wasps_disconnect_req__descriptor,
                                allocator, len, data);
}
void   wasps_disconnect_req__free_unpacked
                     (WaspsDisconnectReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &wasps_disconnect_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   wasps_disconnect_resp__init
                     (WaspsDisconnectResp         *message)
{
  static const WaspsDisconnectResp init_value = WASPS_DISCONNECT_RESP__INIT;
  *message = init_value;
}
size_t wasps_disconnect_resp__get_packed_size
                     (const WaspsDisconnectResp *message)
{
  assert(message->base.descriptor == &wasps_disconnect_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t wasps_disconnect_resp__pack
                     (const WaspsDisconnectResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &wasps_disconnect_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t wasps_disconnect_resp__pack_to_buffer
                     (const WaspsDisconnectResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &wasps_disconnect_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
WaspsDisconnectResp *
       wasps_disconnect_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (WaspsDisconnectResp *)
     protobuf_c_message_unpack (&wasps_disconnect_resp__descriptor,
                                allocator, len, data);
}
void   wasps_disconnect_resp__free_unpacked
                     (WaspsDisconnectResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &wasps_disconnect_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   field_update__init
                     (FieldUpdate         *message)
{
  static const FieldUpdate init_value = FIELD_UPDATE__INIT;
  *message = init_value;
}
size_t field_update__get_packed_size
                     (const FieldUpdate *message)
{
  assert(message->base.descriptor == &field_update__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t field_update__pack
                     (const FieldUpdate *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &field_update__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t field_update__pack_to_buffer
                     (const FieldUpdate *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &field_update__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FieldUpdate *
       field_update__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FieldUpdate *)
     protobuf_c_message_unpack (&field_update__descriptor,
                                allocator, len, data);
}
void   field_update__free_unpacked
                     (FieldUpdate *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &field_update__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor lizard_connect_resp__field_descriptors[3] =
{
  {
    "response_type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(LizardConnectResp, response_type),
    &response_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "character",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(LizardConnectResp, character),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nonce",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(LizardConnectResp, nonce),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lizard_connect_resp__field_indices_by_name[] = {
  1,   /* field[1] = character */
  2,   /* field[2] = nonce */
  0,   /* field[0] = response_type */
};
static const ProtobufCIntRange lizard_connect_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor lizard_connect_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "lizard_connect_resp",
  "LizardConnectResp",
  "LizardConnectResp",
  "",
  sizeof(LizardConnectResp),
  3,
  lizard_connect_resp__field_descriptors,
  lizard_connect_resp__field_indices_by_name,
  1,  lizard_connect_resp__number_ranges,
  (ProtobufCMessageInit) lizard_connect_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lizard_movement_req__field_descriptors[3] =
{
  {
    "character",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(LizardMovementReq, character),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "direction",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(LizardMovementReq, direction),
    &direction__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nonce",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(LizardMovementReq, nonce),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lizard_movement_req__field_indices_by_name[] = {
  0,   /* field[0] = character */
  1,   /* field[1] = direction */
  2,   /* field[2] = nonce */
};
static const ProtobufCIntRange lizard_movement_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor lizard_movement_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "lizard_movement_req",
  "LizardMovementReq",
  "LizardMovementReq",
  "",
  sizeof(LizardMovementReq),
  3,
  lizard_movement_req__field_descriptors,
  lizard_movement_req__field_indices_by_name,
  1,  lizard_movement_req__number_ranges,
  (ProtobufCMessageInit) lizard_movement_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lizard_movement_resp__field_descriptors[3] =
{
  {
    "response_type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(LizardMovementResp, response_type),
    &response_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "score",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(LizardMovementResp, score),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "new_nonce",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(LizardMovementResp, new_nonce),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lizard_movement_resp__field_indices_by_name[] = {
  2,   /* field[2] = new_nonce */
  0,   /* field[0] = response_type */
  1,   /* field[1] = score */
};
static const ProtobufCIntRange lizard_movement_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor lizard_movement_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "lizard_movement_resp",
  "LizardMovementResp",
  "LizardMovementResp",
  "",
  sizeof(LizardMovementResp),
  3,
  lizard_movement_resp__field_descriptors,
  lizard_movement_resp__field_indices_by_name,
  1,  lizard_movement_resp__number_ranges,
  (ProtobufCMessageInit) lizard_movement_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor roaches_connect_req__field_descriptors[2] =
{
  {
    "number",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(RoachesConnectReq, number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scores",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(RoachesConnectReq, n_scores),
    offsetof(RoachesConnectReq, scores),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned roaches_connect_req__field_indices_by_name[] = {
  0,   /* field[0] = number */
  1,   /* field[1] = scores */
};
static const ProtobufCIntRange roaches_connect_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor roaches_connect_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "roaches_connect_req",
  "RoachesConnectReq",
  "RoachesConnectReq",
  "",
  sizeof(RoachesConnectReq),
  2,
  roaches_connect_req__field_descriptors,
  roaches_connect_req__field_indices_by_name,
  1,  roaches_connect_req__number_ranges,
  (ProtobufCMessageInit) roaches_connect_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor roaches_connect_resp__field_descriptors[3] =
{
  {
    "response_type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(RoachesConnectResp, response_type),
    &response_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "characters",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(RoachesConnectResp, n_characters),
    offsetof(RoachesConnectResp, characters),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nonces",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(RoachesConnectResp, n_nonces),
    offsetof(RoachesConnectResp, nonces),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned roaches_connect_resp__field_indices_by_name[] = {
  1,   /* field[1] = characters */
  2,   /* field[2] = nonces */
  0,   /* field[0] = response_type */
};
static const ProtobufCIntRange roaches_connect_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor roaches_connect_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "roaches_connect_resp",
  "RoachesConnectResp",
  "RoachesConnectResp",
  "",
  sizeof(RoachesConnectResp),
  3,
  roaches_connect_resp__field_descriptors,
  roaches_connect_resp__field_indices_by_name,
  1,  roaches_connect_resp__number_ranges,
  (ProtobufCMessageInit) roaches_connect_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor roaches_movement_req__field_descriptors[3] =
{
  {
    "character",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(RoachesMovementReq, character),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "direction",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(RoachesMovementReq, direction),
    &direction__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nonce",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(RoachesMovementReq, nonce),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned roaches_movement_req__field_indices_by_name[] = {
  0,   /* field[0] = character */
  1,   /* field[1] = direction */
  2,   /* field[2] = nonce */
};
static const ProtobufCIntRange roaches_movement_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor roaches_movement_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "roaches_movement_req",
  "RoachesMovementReq",
  "RoachesMovementReq",
  "",
  sizeof(RoachesMovementReq),
  3,
  roaches_movement_req__field_descriptors,
  roaches_movement_req__field_indices_by_name,
  1,  roaches_movement_req__number_ranges,
  (ProtobufCMessageInit) roaches_movement_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor roaches_movement_resp__field_descriptors[2] =
{
  {
    "response_type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(RoachesMovementResp, response_type),
    &response_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "new_nonce",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(RoachesMovementResp, new_nonce),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned roaches_movement_resp__field_indices_by_name[] = {
  1,   /* field[1] = new_nonce */
  0,   /* field[0] = response_type */
};
static const ProtobufCIntRange roaches_movement_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor roaches_movement_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "roaches_movement_resp",
  "RoachesMovementResp",
  "RoachesMovementResp",
  "",
  sizeof(RoachesMovementResp),
  2,
  roaches_movement_resp__field_descriptors,
  roaches_movement_resp__field_indices_by_name,
  1,  roaches_movement_resp__number_ranges,
  (ProtobufCMessageInit) roaches_movement_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor wasps_connect_req__field_descriptors[1] =
{
  {
    "number",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(WaspsConnectReq, number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned wasps_connect_req__field_indices_by_name[] = {
  0,   /* field[0] = number */
};
static const ProtobufCIntRange wasps_connect_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor wasps_connect_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "wasps_connect_req",
  "WaspsConnectReq",
  "WaspsConnectReq",
  "",
  sizeof(WaspsConnectReq),
  1,
  wasps_connect_req__field_descriptors,
  wasps_connect_req__field_indices_by_name,
  1,  wasps_connect_req__number_ranges,
  (ProtobufCMessageInit) wasps_connect_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor wasps_connect_resp__field_descriptors[3] =
{
  {
    "response_type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(WaspsConnectResp, response_type),
    &response_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "characters",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(WaspsConnectResp, n_characters),
    offsetof(WaspsConnectResp, characters),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nonces",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(WaspsConnectResp, n_nonces),
    offsetof(WaspsConnectResp, nonces),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned wasps_connect_resp__field_indices_by_name[] = {
  1,   /* field[1] = characters */
  2,   /* field[2] = nonces */
  0,   /* field[0] = response_type */
};
static const ProtobufCIntRange wasps_connect_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor wasps_connect_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "wasps_connect_resp",
  "WaspsConnectResp",
  "WaspsConnectResp",
  "",
  sizeof(WaspsConnectResp),
  3,
  wasps_connect_resp__field_descriptors,
  wasps_connect_resp__field_indices_by_name,
  1,  wasps_connect_resp__number_ranges,
  (ProtobufCMessageInit) wasps_connect_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor wasps_movement_req__field_descriptors[3] =
{
  {
    "character",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(WaspsMovementReq, character),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "direction",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(WaspsMovementReq, direction),
    &direction__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nonce",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(WaspsMovementReq, nonce),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned wasps_movement_req__field_indices_by_name[] = {
  0,   /* field[0] = character */
  1,   /* field[1] = direction */
  2,   /* field[2] = nonce */
};
static const ProtobufCIntRange wasps_movement_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor wasps_movement_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "wasps_movement_req",
  "WaspsMovementReq",
  "WaspsMovementReq",
  "",
  sizeof(WaspsMovementReq),
  3,
  wasps_movement_req__field_descriptors,
  wasps_movement_req__field_indices_by_name,
  1,  wasps_movement_req__number_ranges,
  (ProtobufCMessageInit) wasps_movement_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor wasps_movement_resp__field_descriptors[2] =
{
  {
    "response_type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(WaspsMovementResp, response_type),
    &response_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "new_nonce",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(WaspsMovementResp, new_nonce),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned wasps_movement_resp__field_indices_by_name[] = {
  1,   /* field[1] = new_nonce */
  0,   /* field[0] = response_type */
};
static const ProtobufCIntRange wasps_movement_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor wasps_movement_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "wasps_movement_resp",
  "WaspsMovementResp",
  "WaspsMovementResp",
  "",
  sizeof(WaspsMovementResp),
  2,
  wasps_movement_resp__field_descriptors,
  wasps_movement_resp__field_indices_by_name,
  1,  wasps_movement_resp__number_ranges,
  (ProtobufCMessageInit) wasps_movement_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lizard_disconnect_req__field_descriptors[2] =
{
  {
    "character",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(LizardDisconnectReq, character),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nonce",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(LizardDisconnectReq, nonce),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lizard_disconnect_req__field_indices_by_name[] = {
  0,   /* field[0] = character */
  1,   /* field[1] = nonce */
};
static const ProtobufCIntRange lizard_disconnect_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor lizard_disconnect_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "lizard_disconnect_req",
  "LizardDisconnectReq",
  "LizardDisconnectReq",
  "",
  sizeof(LizardDisconnectReq),
  2,
  lizard_disconnect_req__field_descriptors,
  lizard_disconnect_req__field_indices_by_name,
  1,  lizard_disconnect_req__number_ranges,
  (ProtobufCMessageInit) lizard_disconnect_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lizard_disconnect_resp__field_descriptors[1] =
{
  {
    "response_type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(LizardDisconnectResp, response_type),
    &response_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lizard_disconnect_resp__field_indices_by_name[] = {
  0,   /* field[0] = response_type */
};
static const ProtobufCIntRange lizard_disconnect_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor lizard_disconnect_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "lizard_disconnect_resp",
  "LizardDisconnectResp",
  "LizardDisconnectResp",
  "",
  sizeof(LizardDisconnectResp),
  1,
  lizard_disconnect_resp__field_descriptors,
  lizard_disconnect_resp__field_indices_by_name,
  1,  lizard_disconnect_resp__number_ranges,
  (ProtobufCMessageInit) lizard_disconnect_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor roaches_disconnect_req__field_descriptors[3] =
{
  {
    "ids",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(RoachesDisconnectReq, n_ids),
    offsetof(RoachesDisconnectReq, ids),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nonces",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(RoachesDisconnectReq, n_nonces),
    offsetof(RoachesDisconnectReq, nonces),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "number",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(RoachesDisconnectReq, number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned roaches_disconnect_req__field_indices_by_name[] = {
  0,   /* field[0] = ids */
  1,   /* field[1] = nonces */
  2,   /* field[2] = number */
};
static const ProtobufCIntRange roaches_disconnect_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor roaches_disconnect_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "roaches_disconnect_req",
  "RoachesDisconnectReq",
  "RoachesDisconnectReq",
  "",
  sizeof(RoachesDisconnectReq),
  3,
  roaches_disconnect_req__field_descriptors,
  roaches_disconnect_req__field_indices_by_name,
  1,  roaches_disconnect_req__number_ranges,
  (ProtobufCMessageInit) roaches_disconnect_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor roaches_disconnect_resp__field_descriptors[1] =
{
  {
    "response_type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(RoachesDisconnectResp, response_type),
    &response_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned roaches_disconnect_resp__field_indices_by_name[] = {
  0,   /* field[0] = response_type */
};
static const ProtobufCIntRange roaches_disconnect_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor roaches_disconnect_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "roaches_disconnect_resp",
  "RoachesDisconnectResp",
  "RoachesDisconnectResp",
  "",
  sizeof(RoachesDisconnectResp),
  1,
  roaches_disconnect_resp__field_descriptors,
  roaches_disconnect_resp__field_indices_by_name,
  1,  roaches_disconnect_resp__number_ranges,
  (ProtobufCMessageInit) roaches_disconnect_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor wasps_disconnect_req__field_descriptors[3] =
{
  {
    "ids",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(WaspsDisconnectReq, n_ids),
    offsetof(WaspsDisconnectReq, ids),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nonces",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(WaspsDisconnectReq, n_nonces),
    offsetof(WaspsDisconnectReq, nonces),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "number",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(WaspsDisconnectReq, number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned wasps_disconnect_req__field_indices_by_name[] = {
  0,   /* field[0] = ids */
  1,   /* field[1] = nonces */
  2,   /* field[2] = number */
};
static const ProtobufCIntRange wasps_disconnect_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor wasps_disconnect_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "wasps_disconnect_req",
  "WaspsDisconnectReq",
  "WaspsDisconnectReq",
  "",
  sizeof(WaspsDisconnectReq),
  3,
  wasps_disconnect_req__field_descriptors,
  wasps_disconnect_req__field_indices_by_name,
  1,  wasps_disconnect_req__number_ranges,
  (ProtobufCMessageInit) wasps_disconnect_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor wasps_disconnect_resp__field_descriptors[1] =
{
  {
    "response_type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(WaspsDisconnectResp, response_type),
    &response_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned wasps_disconnect_resp__field_indices_by_name[] = {
  0,   /* field[0] = response_type */
};
static const ProtobufCIntRange wasps_disconnect_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor wasps_disconnect_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "wasps_disconnect_resp",
  "WaspsDisconnectResp",
  "WaspsDisconnectResp",
  "",
  sizeof(WaspsDisconnectResp),
  1,
  wasps_disconnect_resp__field_descriptors,
  wasps_disconnect_resp__field_indices_by_name,
  1,  wasps_disconnect_resp__number_ranges,
  (ProtobufCMessageInit) wasps_disconnect_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor field_update__field_descriptors[5] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(FieldUpdate, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(FieldUpdate, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "character",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(FieldUpdate, character),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(FieldUpdate, has_id),
    offsetof(FieldUpdate, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "new_score",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(FieldUpdate, has_new_score),
    offsetof(FieldUpdate, new_score),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned field_update__field_indices_by_name[] = {
  2,   /* field[2] = character */
  3,   /* field[3] = id */
  4,   /* field[4] = new_score */
  0,   /* field[0] = x */
  1,   /* field[1] = y */
};
static const ProtobufCIntRange field_update__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor field_update__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "field_update",
  "FieldUpdate",
  "FieldUpdate",
  "",
  sizeof(FieldUpdate),
  5,
  field_update__field_descriptors,
  field_update__field_indices_by_name,
  1,  field_update__number_ranges,
  (ProtobufCMessageInit) field_update__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue response_type__enum_values_by_number[2] =
{
  { "RESPONSE_SUCCESS", "RESPONSE_TYPE__RESPONSE_SUCCESS", 0 },
  { "RESPONSE_FAIL", "RESPONSE_TYPE__RESPONSE_FAIL", 1 },
};
static const ProtobufCIntRange response_type__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex response_type__enum_values_by_name[2] =
{
  { "RESPONSE_FAIL", 1 },
  { "RESPONSE_SUCCESS", 0 },
};
const ProtobufCEnumDescriptor response_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ResponseType",
  "ResponseType",
  "ResponseType",
  "",
  2,
  response_type__enum_values_by_number,
  2,
  response_type__enum_values_by_name,
  1,
  response_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue direction__enum_values_by_number[4] =
{
  { "LEFT", "DIRECTION__LEFT", 0 },
  { "RIGHT", "DIRECTION__RIGHT", 1 },
  { "UP", "DIRECTION__UP", 2 },
  { "DOWN", "DIRECTION__DOWN", 3 },
};
static const ProtobufCIntRange direction__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex direction__enum_values_by_name[4] =
{
  { "DOWN", 3 },
  { "LEFT", 0 },
  { "RIGHT", 1 },
  { "UP", 2 },
};
const ProtobufCEnumDescriptor direction__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Direction",
  "Direction",
  "Direction",
  "",
  4,
  direction__enum_values_by_number,
  4,
  direction__enum_values_by_name,
  1,
  direction__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
