all:
	$(MAKE) -C lizardsNroaches-server
	$(MAKE) -C lizard-client
	$(MAKE) -C roaches-client
	$(MAKE) -C display-app

clean:
	$(MAKE) -C lizardsNroaches-server clean
	$(MAKE) -C lizard-client clean
	$(MAKE) -C roaches-client clean
	$(MAKE) -C display-app clean